project:
  type: website
  output-dir: docs

website:
  title: "Introduction to R Programming Lecture Notes"
  favicon: figures/intro to r logo black.png
  description: "Accompanying webpage with interactive codes and lecture notes for IST3110."
  repo-url: https://github.com/Intro-to-Statistical-Programming-with-R
  repo-actions: [edit, issue]
  repo-subdir: "docs"
  page-navigation: true
  back-to-top-navigation: true

  navbar: 
    # title: false
    logo: figures/intro to r logo black.png
    logo-alt: "Logo for introduction to R Programming"
    right: 
      - href: about.qmd
  sidebar:
    style: 'docked'
    contents:
      - section: Before Starting - Week 0
        contents: 
        - index.qmd
        - 00--01--General--Info.qmd
        - 00--02--Installing--R--and--RStudio.qmd
        - 00--03--Syllabus.qmd
        - 00--04--Evaluation.qmd
        - 00--05--Materials.qmd
        - 00--06--Useful--Websites.qmd
        - 00--07--How--to--use--this--Webpage.qmd
      - section: Week 01 - Introduction to R
        contents: 
          - 01--01--basicsR.qmd
          - 01--01--Data--Types--Main.qmd
          - LabSession01Main.qmd
  page-footer:
    background: light # or `dark`
    left: Copyright 2025, Erhan ÇENE
    right: This website is built with {{< fa heart title="a heart" >}}, {{< fa droplet title="a droplet" >}}, {{< fa face-grin-tears title="a face with tears" >}}, [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/erhancene){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}
    
format:
  live-html:
    theme: 
    - cosmo
    - styles.scss
    # light: cosmo
    # dark: darkly
    mainfont: Nunito
    toc: true
    page-layout: full
